backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: testimonials
    label: Testimonials

    files:
      - label: Client Testimonials
        name: testimonials
        file: data/testimonials.json
        format: json

        fields:
          - label: Testimonials
            name: testimonials
            widget: list

            fields:
              - { label: Name, name: name, widget: string }
              - { label: Designation, name: designation, widget: string }
              - { label: Review, name: review, widget: text }
              - { label: Image, name: image, widget: image }