backend:
  name: git-gateway
  branch: main

local_backend: false

site_url: https://nextgenspeaker.netlify.app
display_url: https://nextgenspeaker.netlify.app
logo_url: /assets/logo.png

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "testimonials"
    label: "Testimonials"

    files:
      - label: "Client Testimonials"
        name: "testimonials"
        file: "_data/testimonials.yml"

        fields:
          - label: "Testimonials"
            name: "testimonials"
            widget: "list"

            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Designation", name: "designation", widget: "string" }
              - { label: "Review", name: "review", widget: "text" }
              - { label: "Image", name: "image", widget: "image" }